services:
  backend:
    image: tdd-mooc-exercise-5-backend
    build: backend
    command: npm start
    volumes:
      - ./backend:/app
      - node_modules_backend:/app/node_modules
    pull_policy: never

  frontend:
    image: tdd-mooc-exercise-5-frontend
    build: frontend
    command: npm run dev -- --host 0.0.0.0
    ports:
      - 127.0.0.1:5173:5173
    volumes:
      - ./frontend:/app
      - node_modules_frontend:/app/node_modules
    pull_policy: never

volumes:
  node_modules_backend:
  node_modules_frontend:
